name: PR checks
on:
  pull_request:
    branches:
      - main
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.0]
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn
    - name: Run
      run: yarn build
    - name: Visual diff tests
      uses: chromaui/action@v1
      # Chromatic GitHub Action options
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        # 👇 Chromatic projectToken, refer to the manage page to obtain it.
        projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}


