name: PR checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
defaults:
  run:
    working-directory: ./apps/lite
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.0]
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn
    - name: Run
      run: yarn build


